### ISSUE TITLE
feat [meta]: issue templating improvements

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2256]
- [x] 1 Ask if it is a normal or business account, 
- [x] 2. Ask if it is happening on MD, normal or both. 
- [x] 3. Automatically parse the config and add it to the easy issue link in the logs
- [x] 4. Automatically determine if this is custom code or running in the EASY API
- [x] 5. `client.getIssueLink()`

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.28.10](https://github.com/open-wa/wa-automate-nodejs/compare/4.28.9...4.28.10) (2022-01-08)

- Release 4.28.10 [`6968f68`](https://github.com/open-wa/wa-automate-nodejs/commit/6968f68627a8f1cc0f0cdab6ca86493a806fc3b6)
- 🔧  update GH bug issue template #2256 [`031c0c2`](https://github.com/open-wa/wa-automate-nodejs/commit/031c0c2640c5e07873aeb527608c8f814b369419)
- ✨ feat: `client.getIssueLink()` #2256 [`34020dc`](https://github.com/open-wa/wa-automate-nodejs/commit/34020dcfdb79ac26c79c3b07b01d027aa8311fd2)
- updated types-only package [`c17dfe9`](https://github.com/open-wa/wa-automate-nodejs/commit/c17dfe905c33cc4b0977a7dcbc70d6066fff9ffb)
